---
# Extract apps.tgz into /srv
# 

- name: Extract apps.tgz into /srv
  hosts: social-vm-app
  remote_user: root
  become: true
  become_method: sudo

  tasks:
    - name: Extract apps.tgz into /srv
      unarchive:
        src: apps.tgz
        dest: /srv
